server:
  port: 10086 # \u7AEF\u53E3
spring:
  application:
    name: eureka-server # \u5E94\u7528\u540D\u79F0\uFF0C\u4F1A\u5728Eureka\u4E2D\u663E\u793A
eureka:
  client:
    register-with-eureka: false # \u662F\u5426\u6CE8\u518C\u81EA\u5DF1\u7684\u4FE1\u606F\u5230EurekaServer\uFF0C\u9ED8\u8BA4\u662Ftrue
    fetch-registry: false # \u662F\u5426\u62C9\u53D6\u5176\u5B83\u670D\u52A1\u7684\u4FE1\u606F\uFF0C\u9ED8\u8BA4\u662Ftrue
    service-url: # EurekaServer\u7684\u5730\u5740\uFF0C\u73B0\u5728\u662F\u81EA\u5DF1\u7684\u5730\u5740\uFF0C\u5982\u679C\u662F\u96C6\u7FA4\uFF0C\u9700\u8981\u52A0\u4E0A\u5176\u5B83Server\u7684\u5730\u5740\u3002
      defaultZone: http://127.0.0.1:${server.port}/eureka
